_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_KEYPOINT_HEAD:
    RELATION_ON: True
    RELATION_DIM: 768
    CONV_HEAD_DIM: 512
    NAME: "KeypointPRHead"
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (120000, 160000)
  MAX_ITER: 180000
