_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHTS: "catalog://ImageNetPretrained/MSRA/R-50"
  MASK_ON: True
  KEYPOINT_ON: True

  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseAMAHead"
    INTER_WEIGHTS: 0.1
#    PART_WEIGHTS: 0.
#    INDEX_WEIGHTS: 0.
    SEMSEG_WEIGHTS: 1.0
#    POINT_REGRESSION_WEIGHTS: 0.
    CONV_HEAD_DIM: 512
    SEMSEG_ON: True
#    KPT_ON: True
  ROI_MASK_HEAD:
    RCNN_HEAD_ON: False
  ROI_KEYPOINT_HEAD:
    RCNN_HEAD_ON: False
  RPN:
    PRE_NMS_TOPK_TRAIN: 1500  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
      BATCH_SIZE_PER_IMAGE: 512
DATASETS:
  TRAIN: ("densepose_coco_2014_train", "densepose_coco_2014_valminusminival")
#  TRAIN: ("densepose_coco_2014_valminusminival",)
  TEST: ("densepose_coco_2014_minival",)
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
  BASE_LR: 0.01
  IMS_PER_BATCH: 4
  WARMUP_FACTOR: 0.1

