_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHTS: "catalog://ImageNetPretrained/MSRA/R-50"
  KEYPOINT_ON: False
  DENSEPOSE_ON: True
  ROI_DENSEPOSE_HEAD:
    CONV_HEAD_DIM: 512
    KPT_ON: False
    PART_WEIGHTS: 1.0
    INDEX_WEIGHTS: 2.0
    POINT_REGRESSION_WEIGHTS: 0.01
    BODY_MASK_WEIGHTS: 5.0
    PREDICTOR: "DensePoseRCNNStarPredictor"
    POOLER_RESOLUTION: 28
    HEATMAP_SIZE: 112
    MID_ON: True
  ROI_KEYPOINT_HEAD:
    RCNN_HEAD_ON: False
  RPN:
    PRE_NMS_TOPK_TRAIN: 1200  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
  BASE_LR: 0.002
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.1
#DATASETS:
#  TRAIN: ("keypoints_coco_2014_train","keypoints_coco_2014_valminusminival")
#  TEST: ("keypoints_coco_2014_minival",)

