_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
#  WEIGHTS: "catalog://ImageNetPretrained/MSRA/R-50"
  WEIGHTS: "/home/wangxuanhan/research/project/detectron2-master/coco_exps/DensePose_kpt_ResNet50_baseline/model_final.pth"
  MASK_ON: True

  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseAMAHead"
    INTER_WEIGHTS: 0.1
#    PART_WEIGHTS: 2.0
#    INDEX_WEIGHTS: 1.0
    SEMSEG_WEIGHTS: 1.0
    CONV_HEAD_DIM: 256
    SEMSEG_ON: True
    IA_LOSS: True
  ROI_MASK_HEAD:
    RCNN_HEAD_ON: False
  RPN:
    PRE_NMS_TOPK_TRAIN: 1200  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
      BATCH_SIZE_PER_IMAGE: 384
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
  BASE_LR: 0.002
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.1

