_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  MASK_ON: True
  KEYPOINT_ON: True
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 0.5
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseAMAHead"
    INTER_WEIGHTS: 0.1
#    PART_WEIGHTS: 2.0
#    INDEX_WEIGHTS: 1.0
    SEMSEG_WEIGHTS: 1.0
    CONV_HEAD_DIM: 256
    SEMSEG_ON: True
    IA_LOSS: True
    KPT_ON: True
    KPT_UP_SCALE: 4
    FG_IOU_THRESHOLD: 0.65

  ROI_MASK_HEAD:
    RCNN_HEAD_ON: False
  ROI_KEYPOINT_HEAD:
    RCNN_HEAD_ON: False
    LOSS_WEIGHT: 0.1
  RPN:
    PRE_NMS_TOPK_TRAIN: 1200  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
      BATCH_SIZE_PER_IMAGE: 384
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
  BASE_LR: 0.002
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.01

