_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHTS: "/home/wangxuanhan/research/project/detectron2-master/coco_dp_exps/ResNet50_fpn_Kpt_Net_1lx/model_final.pth"
#  WEIGHTS: "catalog://ImageNetPretrained/MSRA/R-50"
  KEYPOINT_ON: True
  DENSEPOSE_ON: True
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 0.5
  ROI_DENSEPOSE_HEAD:
    CONV_HEAD_DIM: 512
    KPT_ON: True
    RCNN_HEAD_ON: True
      #    PART_WEIGHTS: 2.0
      #    INDEX_WEIGHTS: 1.0
#    SEMSEG_WEIGHTS: 1.0
    UP_SCALE: 2
    KPT_CLASSIFIER_WEIGHT_DIR: "/home/wangxuanhan/research/project/detectron2-master/coco_dp_exps/ResNet50_fpn_Kpt_Net_1lx/kpt_classifier.pkl"
#    PREDICTOR: "DensePoseKptRelationPredictor"
    PREDICTOR: "DensePoseKptRelationPredictorV2"
    KPT_SURF_RELATION_DIR: "/home/wangxuanhan/research/project/visual_genome_python_driver/kpt_surface_relationships.pkl"
  ROI_KEYPOINT_HEAD:
    RCNN_HEAD_ON: False
    LOSS_WEIGHT: 0.5
#  ROI_HEADS:
#    SCORE_THRESH_TEST: 0.1
#TEST:
#  DETECTIONS_PER_IMAGE: 20
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
  BASE_LR: 0.002
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.1
#DATASETS:
#  TRAIN: ("keypoints_coco_2014_train","keypoints_coco_2014_valminusminival")
#  TEST: ("keypoints_coco_2014_minival",)

