_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHTS: "models/Keypoints_KTN_Weights.pth"
  KEYPOINT_ON: True
  DENSEPOSE_ON: True
  ROI_DENSEPOSE_HEAD:
    CONV_HEAD_DIM: 512
    KPT_ON: True
    PART_WEIGHTS: 1.0
    INDEX_WEIGHTS: 2.0
    POINT_REGRESSION_WEIGHTS: 0.01
    BODY_MASK_WEIGHTS: 5.0
    KPT_CLASSIFIER_WEIGHT_DIR: "models/keypoints_kpt_classifier_weights.pkl"
    KPT_SURF_RELATION_DIR: "models/kpt_surface_relationships.pkl"
    PREDICTOR: "DensePoseKptRelationPredictor"
    POOLER_RESOLUTION: 28
    HEATMAP_SIZE: 112
    UP_SCALE: 2
    KPT_UP_SCALE: 2
    MID_ON: True
    FG_IOU_THRESHOLD: 0.65
    FG_MASK_THRESHOLD: 0.3
  ROI_KEYPOINT_HEAD:
    RCNN_HEAD_ON: False
    LOSS_WEIGHT: 0.5
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
  BASE_LR: 0.01
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.1

