_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHTS: "/home/wangxuanhan/research/project/detectron2-master/coco_dp_exps/ResNet50_fpn_MID_Kpt_Net_1lx/model_final.pth"
#  WEIGHTS: "catalog://ImageNetPretrained/MSRA/R-50"
  KEYPOINT_ON: True
  DENSEPOSE_ON: True
  ROI_DENSEPOSE_HEAD:
    NAME: DensePoseDeepLabHead
    CONV_HEAD_DIM: 512
    KPT_ON: True
#    PART_WEIGHTS: 0.3
#    INDEX_WEIGHTS: 2.0
#    POINT_REGRESSION_WEIGHTS: 0.1
#    BODY_MASK_WEIGHTS: 2.0
    KPT_CLASSIFIER_WEIGHT_DIR: "/home/wangxuanhan/research/project/detectron2-master/coco_dp_exps/ResNet50_fpn_MID_Kpt_Net_1lx/kpt_classifier.pkl"
    KPT_SURF_RELATION_DIR: "/home/wangxuanhan/research/project/visual_genome_python_driver/kpt_surface_relationships.pkl"
    PREDICTOR: "DensePoseKptRelationPredictorV3"
    POOLER_RESOLUTION: 28
    HEATMAP_SIZE: 112
    UP_SCALE: 2
    KPT_UP_SCALE: 1
    MID_ON: True
#    FG_IOU_THRESHOLD: 0.65
  ROI_KEYPOINT_HEAD:
    RCNN_HEAD_ON: False
    LOSS_WEIGHT: 0.5
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
#  MAX_ITER: 180000
#  STEPS: (120000, 160000)
  BASE_LR: 0.002
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.1
#DATASETS:
#  TRAIN: ("keypoints_coco_2014_train","keypoints_coco_2014_valminusminival")
#  TEST: ("keypoints_coco_2014_minival",)

