_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHTS: "/home/wangxuanhan/research/project/detectron2-master/coco_dp_exps/ResNeXt101_32x8d_fpn_MID_Kpt_Net_1lx/model_final.pth"
#  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  KEYPOINT_ON: True
  DENSEPOSE_ON: True
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_DENSEPOSE_HEAD:
    CONV_HEAD_DIM: 512
    KPT_ON: True
    PART_WEIGHTS: 1.0
    INDEX_WEIGHTS: 2.0
    POINT_REGRESSION_WEIGHTS: 0.01
    BODY_MASK_WEIGHTS: 5.0
    KPT_CLASSIFIER_WEIGHT_DIR: "/home/wangxuanhan/research/project/detectron2-master/coco_dp_exps/ResNet50_fpn_MID_Kpt_Net_1lx/kpt_classifier.pkl"
    KPT_SURF_RELATION_DIR: "/home/wangxuanhan/research/project/visual_genome_python_driver/kpt_surface_relationships.pkl"
    PREDICTOR: "DensePoseKptRelationPredictor"
    POOLER_RESOLUTION: 28
    HEATMAP_SIZE: 112
    UP_SCALE: 2
    KPT_UP_SCALE: 2
    MID_ON: True
#    FG_IOU_THRESHOLD: 0.65
  ROI_KEYPOINT_HEAD:
    RCNN_HEAD_ON: False
    LOSS_WEIGHT: 0.5
#  RPN:
#    PRE_NMS_TOPK_TRAIN: 1200  # Per FPN level
#    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
#    POST_NMS_TOPK_TRAIN: 1000
#    POST_NMS_TOPK_TEST: 1000
#  ROI_HEADS:
#    BATCH_SIZE_PER_IMAGE: 384
SOLVER:
#  MAX_ITER: 260000
#  STEPS: (200000, 240000)
  MAX_ITER: 180000
  STEPS: (120000, 160000)
  BASE_LR: 0.01
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.1
#DATASETS:
#  TRAIN: ("keypoints_coco_2014_train","keypoints_coco_2014_valminusminival")
#  TEST: ("keypoints_coco_2014_minival",)

